# Simple workflow for deploying static content to GitHub Pages with Vite
name: Deploy Nefert's Nail Salon to GitHub Pages

on:
  push:
    branches: ["main"]

  # Allows manually running this workflow from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queue.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Production Bundle
        run: npm run build

      - name: Configure GitHub Pages Settings
        uses: actions/configure-pages@v4

      - name: Upload Generated Output
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy static assets
        id: deployment
        uses: actions/deploy-pages@v4
